spring:
  application:
    name: securityTemplate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securityTemplate?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 10100

system:
  security:
    permitUrls:
      - "/user/login"
      - "/user/register"
      - "/user/recoverPassword"
      - "/file/upload"
    maximumSessions: 1
    maxSessionsPreventsLogin: false
  custom:
    jwtSecretKey: u7ydpT2P3eVf6W8xN9sKrG4tQ1vZw5bA6hXmJkCcRfM
